// app/src/lib/components/filetree/FileTree.tsx
import Folder from "./Folder"
import type { TreeNode } from "../../types/tree"

interface FileTreeProps {
	data: TreeNode[]
}

export default function FileTree({ data }: FileTreeProps) {
	return (
		<div className="flex flex-col p-1 select-none">
			{data.map((datum) => (
				<Folder key={datum.id} title={datum.title} nodes={datum.children ?? []} />
			))}
		</div>
	)
}

// src/lib/components/filetree/FileTree.svelte
<script lang="ts">
	import Folder from '$lib/components/filetree/Folder.svelte';
	import type { TreeNode } from '$lib/types/tree';

	export let data: TreeNode[] = [];

	let expandedNodes: string[] = [];
</script>

<ul class="flex flex-col py-2">
	{#each data as datum, _ (datum.id)}
		<li>
			<Folder title={datum.title} nodes={datum.children ?? []} />
		</li>
	{/each}
</ul>
