// vue/src/components/sessions/Session-Card.vue
<template>
  <div
    class="relative flex justify-between w-full h-40 overflow-hidden transition-all duration-200 ease-in-out rounded-sm shadow-md  bg-gray-50 dark:bg-black ring-2 ring-offset-2 ring-offset-gray-50 dark:ring-offset-black ring-gray-700 dark:ring-gray-300 group"
  >
    <div class="flex flex-col h-full lg:w-7/12">
      <div
        v-if="info.images[0]"
        class="absolute overflow-hidden rounded-sm inset-2"
      >
        <img
          :src="info.images[0].image"
          :loading="index > 5 ? 'lazy' : 'eager'"
          :alt="info.images[0].alt"
          class="inline-block object-cover w-full h-full transition-transform  transform-gpu group-hover:scale-110"
        />
        <div
          class="absolute inset-0 w-full h-full  opacity-60 bg-gradient-to-br from-gray-900 to-transparent"
        />
      </div>
      <div class="w-10 h-1" :style="`background-color: ${color}`" />
      <div
        class="absolute bottom-0 right-0 w-10 h-1"
        :style="`background-color: ${color}`"
      />

      <div class="absolute m-4 leading-5">
        <h2
          class="mb-2 text-4xl font-medium font-cursive"
          :class="[
            info.images[0] ? 'text-gray-50' : 'text-gray-700 dark:text-gray-50',
          ]"
        >
          <g-link :to="info.path">
            {{ info.title }}
          </g-link>
        </h2>
        <small
          class="font-semibold tracking-wider"
          :class="[info.images[0] ? 'text-gray-300' : 'text-gray-600']"
          >{{ info.date }}
        </small>
        <p
          class="mt-2 text-lg tracking-wide"
          :class="[
            info.images[0] ? 'text-gray-200 text-shadow-md' : 'text-gray-600',
          ]"
        >
          {{ info.excerpt }}
        </p>
      </div>
      <div class="absolute bottom-3 right-3 h-6 flex flex-nowrap space-x-1.5">
        <TagBadge v-for="tag in info.tags" :key="tag.title" :tag="tag" />
      </div>
    </div>
  </div>
</template>

<script>
  export default {
    components: {
      TagBadge: () => import('../tags/Tag-Badge.vue'),
    },
    props: {
      info: Object,
      index: Number,
    },
    computed: {
      color() {
        return this.info.style[0]?.category.color;
      },
    },
  };
</script>

// app/src/lib/components/SessionCard.svelte
<script lang="ts">
	import type { SessionPreviewWithFeatureImage } from '$lib/types/session';
	import { buildLink } from '$lib/utils/BuildLinkToGivenCollectionNode';

	export let session: SessionPreviewWithFeatureImage;
</script>

<article
	class="box-border relative w-full overflow-hidden border group h-28 rounded-2xl border-white/5 bg-heicha-700 bg-opacity-40"
>
	<a sveltekit:prefetch href={buildLink(session)} class="flex flex-row divide-x-2 divide-white/5">
		<div class="flex flex-col justify-center flex-shrink-0 w-40 h-full overflow-hidden">
			<img
				src={session.images?.[0].image}
				alt={session.images?.[0].alt}
				class="object-cover image-zoom"
			/>
		</div>
		<div class="p-5">
			<h3 class="text-2xl">
				{#if session.production_year}
					<span class="opacity-80 group-hover:opacity-100 group-hover:text-white">
						{session.production_year}
					</span>
				{/if}
				<span class="opacity-80 group-hover:opacity-100 group-hover:text-tea-soup-500">
					{session.title}
				</span>
			</h3>
			<p class="text-bai-cha-200 opacity-60 group-hover:opacity-80">{session.excerpt}</p>
		</div>
	</a>
	<div class="absolute top-2.5 right-2.5">
		<span
			class="block w-3 h-3 rounded-2xl"
			style="background-color: {session?.style?.[0]?.category.color}"
		/>
	</div>
</article>
