// src/lib/components/SiteHeader.svelte
<script>
	import Github from '$lib/components/icons/Github.svelte';
	import Instagram from '$lib/components/icons/Instagram.svelte';
</script>

<header class="flex flex-row justify-between px-4 py-1 font-display">
	<a sveltekit:prefetch href="/" aria-label="home" class="pointer-events-auto">
		<h1 class="text-6xl leading-[3.25rem] text-bai-cha-100 select-none drop-shadow-split">
			<span>puerh</span>
			<br />
			<span class="block -ml-4">.wtf</span>
		</h1>
	</a>

	<div class="flex flex-col space-y-1.5 m-auto pt-4 opacity-80">
		<a
			aria-label="source code"
			href="https://github.com/tonyketcham/puerh.wtf"
			class="w-5 h-5 outline-none focus:outline-none hover:text-tea-soup-500 focus:text-tea-soup-500"
		>
			<Github />
		</a>

		<a
			aria-label="puerh.wtf instagram"
			href="https://instagram.com/puerh.wtf/"
			class="w-5 h-5 outline-none focus:outline-none hover:text-tea-soup-500 focus:text-tea-soup-500"
		>
			<Instagram />
		</a>
	</div>
</header>

// app/src/lib/components/SiteHeader.tsx
import Link from "next/link"
import Github from "./icons/Github"
import Instagram from "./icons/Instagram"

export default function SiteHeader() {
	return (
		<header className="flex flex-row justify-between px-4 py-1 font-display">
			<Link href="/" aria-label="home" className="pointer-events-auto">
				<h1 className="text-6xl leading-[3.25rem] text-bai-cha-100 select-none drop-shadow-split">
					<span>puerh</span>
					<br />
					<span className="block -ml-4">.wtf</span>
				</h1>
			</Link>

			<div className="flex flex-col space-y-1.5 m-auto pt-4 opacity-80">
				<a
					aria-label="source code"
					href="https://github.com/tonyketcham/puerh.wtf"
					className="w-5 h-5 outline-none focus:outline-none hover:text-tea-soup-500 focus:text-tea-soup-500 pointer-events-auto"
				>
					<Github />
				</a>

				<a
					aria-label="puerh.wtf instagram"
					href="https://instagram.com/puerh.wtf/"
					className="w-5 h-5 outline-none focus:outline-none hover:text-tea-soup-500 focus:text-tea-soup-500 pointer-events-auto"
				>
					<Instagram />
				</a>
			</div>
		</header>
	)
}
