// app/src/lib/components/containers/Panel.tsx
"use client"

import { useRef, useState } from "react"

interface PanelProps {
	id?: string
	children: React.ReactNode
	header?: React.ReactNode
}

export default function Panel({ id = "", children, header }: PanelProps) {
	const [isDragging, setIsDragging] = useState(false)
	const [offset, setOffset] = useState({ x: 0, y: 0 })
	const handleRef = useRef<HTMLDivElement>(null)

	const handleMouseDown = () => {
		setIsDragging(true)
	}

	const handleMouseUp = () => {
		setIsDragging(false)
	}

	const handleDoubleClick = () => {
		setOffset({ x: 0, y: 0 })
	}

	return (
		<section
			id={id}
			className={`flex flex-col w-full flex-grow overflow-hidden h-full rounded-2xl border border-heicha-500 box-border bg-heicha-700 backdrop-brightness-50 backdrop-blur-[48px] transition-opacity duration-200 ease-in-out ${
				isDragging ? "bg-opacity-80 border-white/30" : "bg-opacity-40"
			}`}
			style={{
				boxShadow: "0px 8px 14px rgba(0, 0, 0, 0.1)",
				transform: `translate(${offset.x}px, ${offset.y}px)`,
			}}
		>
			{header && (
				<div
					ref={handleRef}
					className={`bg-heicha-600/5 py-3 px-4 border-b cursor-grab pointer-events-auto ${
						isDragging ? "cursor-grabbing border-white/30" : "cursor-grab border-heicha-500"
					}`}
					onMouseDown={handleMouseDown}
					onMouseUp={handleMouseUp}
					onDoubleClick={handleDoubleClick}
				>
					{header}
				</div>
			)}
			<div
				className="max-h-full pointer-events-auto overscroll-y-auto"
				style={{ overflowY: "auto" }}
			>
				{children}
			</div>
		</section>
	)
}

// app/src/lib/components/containers/Panel.svelte
<script lang="ts">
	import { draggable } from '@neodrag/svelte';
	import { getContext, onMount } from 'svelte';

	export let id = '';

	const { getSiteContent } = getContext('siteContent');
	let siteContentContainer: HTMLElement;

	onMount(() => {
		siteContentContainer = getSiteContent();
	});

	let handle: HTMLDivElement;
	let offset: { x: number; y: number } = { x: 0, y: 0 };
	let isDragging = false;
</script>

<section
	{id}
	class="flex flex-col w-full flex-grow overflow-hidden h-full rounded-2xl border border-white/5 box-border bg-heicha-700 backdrop-brightness-50 backdrop-blur-[48px] transition-opacity duration-200 ease-in-out {isDragging
		? 'bg-opacity-80 border-white/30'
		: 'bg-opacity-40'}"
	style="box-shadow: 0px 8px 14px rgba(0, 0, 0, 0.1);"
	use:draggable={{
		axis: 'both',
		bounds: 'body',
		handle,
		defaultClassDragging: 'bg-heicha-700/80',
		position: { x: offset.x, y: offset.y },
		onDragEnd: ({ offsetX, offsetY }) => {
			offset = { x: offsetX, y: offsetY };
		}
	}}
>
	{#if $$slots.header}
		<div
			bind:this={handle}
			class="bg-heicha-600/5 py-3 px-4 border-b cursor-grab pointer-events-auto {isDragging
				? 'curosr-grabbing border-white/30'
				: 'cursor-grab border-white/5'}"
			on:wheel={(e) => {
				siteContentContainer.scrollTop += e.deltaY;
			}}
			on:mousedown={() => {
				isDragging = true;
			}}
			on:mouseup={() => {
				isDragging = false;
			}}
			on:dblclick={() => {
				offset = { x: 0, y: 0 };
			}}
		>
			<slot name="header" />
		</div>
	{/if}
	<div class="max-h-full overscroll-y-auto pointer-events-auto" style="overflow-y: overlay">
		<slot />
	</div>
</section>
